version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./src:/src
        command:
            sh -c "python manage.py runserver 0.0.0.0:8000"
#docker-compose build
#docker-compose run [app (line 4)] sh -c "django-admin.py startproject apiprotect ."
#docker-compose run app sh -c "django-admin.py startproject apiprotect ."